
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: haskell
      options: --user root

    steps:
     - name: Install Stack
       run: stack upgrade

     - name: Run Stack tests
       run: stack test
