
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Install Stack
       run: curl -sSL https://get.haskellstack.org/ | sh

     - name: Run Stack tests
       run: stack --test
