
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: haskell
      options: --user root

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Print wd
       run: pwd

     - name: Run Stack tests
       run: mkdir /root/.stack && stack --stack-root /root/.stack test
