
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: haskell

    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Upgrade Stack
       run: stack upgrade

     - name: Run Stack tests
       run: stack test
