
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: haskell
      options: --user root

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Run Stack tests
       run: mkdir -p /root/.stack && cp -r $GITHUB_WORKSPACE /root/gh-ci-tests && cd /root/gh-ci-tests && stack --stack-root /root/.stack upgrade && stack --stack-root /root/.stack test 
