
name: Haskell Stack Tests

on:
  - push
  - pull_request
permissions:
  checks: write
  actions: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: 
      image: haskell
      options: --user root

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Echo github-workspace dir
       run: echo $GITHUB_WORKSPACE

     - name: Run Stack tests
       run: sudo stack test
